#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-Mock
version:      0.19
version_from: VERSION
installdirs:  site
requires:
    DBI:                           1.3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
